### ISSUE TITLE
Missing this C: drive path

### ISSUE THREAD

**Issue by Chunjee** [FastAsFack/DiscordHelpSaver#1]
https://github.com/FastAsFack/DiscordHelpSaver/blob/baa10e2fa85499c8c0da438381c28ef28f62f3ae/DiscordHelpSaver.ahk2#L26

**Comment by FastAsFack** [comment]
that should be fixed as of now i copied all of the code over from my own library but i forgot to look over the whole code for paths like that so yea 🤦
